services:
  canvas-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CANVAS_API_URL=${CANVAS_API_URL}
      - CANVAS_API_TOKEN=${CANVAS_API_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped 